<?php

namespace App\Repositories;

use App\Models\User;
use File;
use Hash;
use Illuminate\Http\UploadedFile;
use Image;

class UserRepository extends BaseRepository
{
    /**
     * @var array
     */
    protected $fieldSearchable = [
        'name',
        'email',
        'image',
        'is_active',
        'is_admin'
    ];

    /**
     * Configure the Model
     **/
    public function model()
    {
        return User::class;
    }

    /**
     * @param array $attributes
     * @return mixed
     */
    public function save(array $attributes)
    {
        unset($attributes['image']);
        $attributes['password'] = Hash::make($attributes['password']);
        return User::create($attributes); // TODO: Change the autogenerated stub
    }

    /**
     * @param User $user
     * @param UploadedFile $image
     * @return User
     */
    public function updateUserImage($user, $image)
    {
        if ($image) {
            $imageName = $user->id . '_' . time() . '.' . $image->getClientOriginalExtension();

            $destinationPath = public_path('profiles');

            File::makeDirectory($destinationPath, 0777, true, true);

            $img = Image::make($image->getRealPath());
            $img->resize(150, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save($destinationPath . '/' . $imageName);

            $oldImage = $user->image;


            $user->image = $imageName;
            $user->save();

            if (file_exists($oldImage = public_path('profiles/' . $oldImage))) {
                unlink($oldImage);
            }
        }

        return $user;
    }
}
